on: 
  workflow_call:
    inputs:
      username:
        description: user name
        default: John Ceina
        required: true
        type: string
jobs:
  print_messadge:
    runs-on: ubuntu-latest
    steps:
    - name: Prnt the user name to the STDOUT
      run: echo "username is ${{inputs.username}}"
    
        
