name: My first job

on: push

jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v5
          
        - name: Welcome Message
          run: echo "My First Github Actions workflow jon"

        - name: list files
          run: ls

        - name: Read file
          run: cat README.md