name: exploring matirx configuration
on:
  workflow_dispatch:
  push:

jobs:
  docker:
    strategy:
       fail-fast: false
       max-parallel: 2
       matrix:
        os: [ubuntu-latest,ubuntu-22.04,windows-latest] 
        image: [hello-world, alpine]
        exclude:
          - image : alpine
            os: windows-latest
        include:
          - image: amd64/alpine
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Echo Docker Info
        run: docker info
      - name: Run Docker Image on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}

     

