name: exploring matirx configuration
on:
  workflow_dispatch:
  push:

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    strategy:
       matrix:
        os: [ubuntu-latest,ubuntu-20.04,windows-latest] 
        image: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Echo Docker Info
        run: docker info
      - name: Run Docker Image on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}
     