name:build-test-deploy
on: 
  workflow_call:
    node-version:
      description: "Node version"
      required: true
      type: string
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - name: Checkout version
      uses: actions/checkout@v3
    - name: node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: install dependencies
      run: npm install
    - name: build node.js
      run: npm run build
  test:
    needs: build
      runs-on:  ubuntu-latest
    steps:
    - name: Checkout version
      uses: actions/checkout@v3
    - name: node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: install dependencies
      run: npm install
    - name: test
      run: npm test
      
